/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 librarians_room.glb -T 
Files: librarians_room.glb [1.72MB] > C:\VS projects\portfolio\Portfolio-site\public\models\librarians_room-transformed.glb [175.88KB] (90%)
Author: daydev (https://sketchfab.com/daydev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/librarians-room-5363dd8100c64cb2a99b5619b7d78610
Title: Librarian's Room
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/librarians_room-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Room_Wall_0.geometry}
        material={materials.Wall}
        position={[12.096, 11.584, -59.541]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={194.179}
      />
      <mesh
        geometry={nodes.Room_Floor_0.geometry}
        material={materials.Floor}
        position={[12.096, 11.584, -59.541]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={194.179}
      />
      <mesh
        geometry={nodes.Room_Windows_0.geometry}
        material={materials.PaletteMaterial001}
        position={[12.096, 11.584, -59.541]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={194.179}
      />
      <mesh
        geometry={nodes.Table_Table_0.geometry}
        material={materials.Table}
        position={[169.704, -114.937, -229.054]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={8.501}
      />
      <mesh
        geometry={nodes.Cube_Bed_0.geometry}
        material={materials.PaletteMaterial002}
        position={[-101.408, -101.92, -175.955]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={47.299}
      />
      <mesh
        geometry={nodes.Cube_Bed2_0.geometry}
        material={materials.Bed2}
        position={[-101.408, -101.92, -175.955]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={47.299}
      />
      <mesh
        geometry={nodes.Book_CoverA_0.geometry}
        material={materials.CoverA}
        position={[118.938, 77.76, -199.278]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={21.466}
      />
      <mesh
        geometry={nodes.Book004_CoverB_0.geometry}
        material={materials.CoverB}
        position={[195.574, 58.736, -199.278]}
        rotation={[Math.PI, -1.073, 0]}
        scale={18.48}
      />
      <mesh
        geometry={nodes.Cube004_Mac_0.geometry}
        material={materials.material_17}
        position={[136.249, -43.814, -191.086]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={31.477}
      />
      <mesh
        geometry={nodes.Cube004_Keyboard_0.geometry}
        material={materials.Keyboard}
        position={[136.249, -43.814, -191.086]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={31.477}
      />
      <mesh
        geometry={nodes.Cube004_Desktop_0.geometry}
        material={materials.Desktop}
        position={[136.249, -43.814, -191.086]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={31.477}
      />
      <mesh
        geometry={nodes.Cube005_Wardrop_0.geometry}
        material={materials.Wardrop}
        position={[-121.448, -117.042, 168.738]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={35.528}
      />
      <mesh
        geometry={nodes.Cube007_Images_0.geometry}
        material={materials.Images}
        position={[-38.039, 54.159, -219.983]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={51.093}
      />
      <mesh
        geometry={nodes.Lamp_Bulb001_Lamp_Bulb_0.geometry}
        material={materials.PaletteMaterial003}
        position={[-143.294, 101.898, -218.151]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={416.126}
      />
    </group>
  );
}

useGLTF.preload("/models/librarians_room-transformed.glb");

export default Model;
